language: node_js
node_js:
  - "10"
before_script:
  - cd note-me-ui
  - export NG_CLI_ANALYTICS=ci
  - npm install -g @angular/cli
  - npm install
jobs:
  allow_failures:
    - env: ALLOW_FAIL="-ALLOW_FAIL"
  include:
    - stage: build
      script: npm run build
    - stage: linter
      env: 
        ALLOW_FAIL="-ALLOW_FAIL"
      script: ng lint